[tool.poetry]
name = "hades-pathrag"
version = "0.1.0"
description = "HADES-PathRAG integration with XnX notation"
authors = ["HADES Team"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
# Core dependencies
aiohttp = "^3.8.5"
httpx = "^0.27.0"
fastapi = "^0.100.0"
pydantic = "^2.0.0"
uvicorn = "^0.23.0"
python-multipart = "^0.0.6"
python-dotenv = "^1.0.0"
python-arango = "^7.5.0"
networkx = "^3.0"
sqlalchemy = "^2.0.0"
tenacity = "^8.2.0"
openai = "^1.0.0"
ollama = "^0.1.8"  # Ollama Python client
aioboto3 = "^14.1.0"
tqdm = "^4.67.1"
numpy = "^1.25.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-cov = "*"
black = "^23.0.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hades-mcp-server = "src.mcp.server:main"
