---
# Pipeline Configuration File
# Controls behavior of parallel processing pipelines

# Global pipeline settings
pipeline:
  mode: "training"  # training or inference
  save_intermediate_results: true
  output_dir: "./test-output"
  device_config:
    CUDA_VISIBLE_DEVICES: ""  # Empty string to force CPU, comma-separated device IDs for GPU (e.g., "0,1"), or null for system default

# Device execution configurations
# Either gpu_execution or cpu_execution should have enabled: true, but not both
gpu_execution:
  enabled: false  # Master toggle for GPU mode
  docproc:
    device: "cuda:0"
    batch_size: 4
  chunking:
    device: "cuda:0"
    batch_size: 8
  embedding:
    device: "cuda:0"
    batch_size: 8
    model_precision: "float16"  # Options: float32, float16, bfloat16
  isne:
    device: "cuda:0"
    batch_size: 32
    model_precision: "float32"  # ISNE typically works better with float32

cpu_execution:
  enabled: true   # Enabled for CPU-based processing
  docproc:
    device: "cpu"
    num_threads: 8
  chunking:
    device: "cpu"
    num_threads: 8
  embedding:
    device: "cpu"
    num_threads: 8
  isne:
    device: "cpu"
    num_threads: 4

# Worker thread pools
workers:
  docproc: 
    count: 8
    timeout_seconds: 600
  chunking:
    count: 16
    timeout_seconds: 300
  embedding:
    count: 6  # Fewer since this is GPU-bound
    timeout_seconds: 300
  isne:
    count: 4
    timeout_seconds: 600

# Queue configurations
queues:
  docproc_output:
    max_size: 50           # Maximum items in queue
    max_memory_mb: 16384   # Larger value for high-RAM system
    backpressure_threshold: 0.8  # When to start applying backpressure
    backoff_strategy: "exponential"  # linear, exponential
    backoff_base_seconds: 0.1
    backoff_max_seconds: 5.0
  
  chunking_output:
    max_size: 100
    max_memory_mb: 32768   # Chunks can use more memory
    backpressure_threshold: 0.7
    backoff_strategy: "exponential"
    backoff_base_seconds: 0.1
    backoff_max_seconds: 5.0
  
  embedding_output:
    max_size: 200
    max_memory_mb: 65536   # Embeddings use significant memory
    backpressure_threshold: 0.6
    backoff_strategy: "exponential"
    backoff_base_seconds: 0.1
    backoff_max_seconds: 5.0

# Monitoring settings
monitoring:
  check_interval_seconds: 5
  metrics_log_interval_seconds: 30
  enable_memory_warnings: true
  memory_warning_threshold_percent: 85

# Processing limits - useful for testing different corpus sizes
limits:
  max_documents: null      # null = no limit
  max_chunks_per_document: null
  max_tokens_per_chunk: 2048

# ISNE (Inductive Shallow Node Embedding) configuration
isne:
  # Model configuration
  model:
    embedding_dim: 768       # Input dimension from ModernBERT
    hidden_dim: 256          # Hidden representation size
    output_dim: 768          # Final embedding dimension (matches input for compatibility)
    num_layers: 2            # Number of ISNE layers
    num_heads: 8             # Number of attention heads
    dropout: 0.1             # Dropout rate for regularization
    activation: "elu"        # Activation function (options: elu, relu, leaky_relu)
    add_self_loops: true     # Whether to add self-loops to graph edges

  # Training configuration
  training:
    learning_rate: 0.001     # Initial learning rate
    weight_decay: 1e-5       # L2 regularization
    epochs: 50               # Maximum number of training epochs
    batch_size: 32           # Batch size for training
    num_hops: 1              # Number of hops for neighborhood sampling
    neighbor_size: 10        # Maximum number of neighbors to sample per node
    eval_interval: 5         # Interval for evaluation during training
    early_stopping_patience: 10  # Patience for early stopping
    checkpoint_interval: 5   # Interval for model checkpointing
    device: "cpu"            # Default device (overridden by global CPU/GPU settings)
    
    # Loss weights
    lambda_feat: 1.0         # Weight for feature preservation loss
    lambda_struct: 1.0       # Weight for structural preservation loss  
    lambda_contrast: 0.5     # Weight for contrastive loss

  # Graph construction parameters
  graph:
    similarity_threshold: 0.7  # Minimum similarity for connecting nodes
    max_neighbors: 5         # Maximum number of neighbors per node based on similarity
    sequential_weight: 0.9   # Edge weight for sequential connections
    similarity_weight: 0.7   # Base weight for similarity-based connections
    window_size: 3           # Window size for sequential context connections

  # Directory configuration
  directories:
    data_dir: "./data/isne"              # Base directory for ISNE data
    input_dir: "./test-output/pipeline-mp-test"  # Default input directory
    output_dir: "./test-output/isne-training"    # Default output directory
    model_dir: "./models/isne"                   # Directory for model storage
  
  # Model naming and versioning
  model:
    name_prefix: "isne_model"            # Prefix for model filenames
    version: "v1"                        # Model version identifier
    use_timestamp: true                  # Whether to include timestamp in filename
    keep_previous_versions: true         # Whether to keep previous model versions

# Performance profiles - quick selection of preset configurations
profiles:
  high_throughput:
    workers:
      docproc:
        count: 16
      chunking:
        count: 32
      embedding:
        count: 8
    queues:
      docproc_output:
        max_memory_mb: 65536
      chunking_output:
        max_memory_mb: 98304
      embedding_output:
        max_memory_mb: 131072
  
  balanced:
    workers:
      docproc:
        count: 8
      chunking:
        count: 16
      embedding:
        count: 6
    queues:
      docproc_output:
        max_memory_mb: 16384
      chunking_output:
        max_memory_mb: 32768
      embedding_output:
        max_memory_mb: 65536
  
  low_memory:
    workers:
      docproc:
        count: 4
      chunking:
        count: 8
      embedding:
        count: 2
    queues:
      docproc_output:
        max_memory_mb: 4096
      chunking_output:
        max_memory_mb: 8192
      embedding_output:
        max_memory_mb: 16384
